#!/bin/bash

set -uo pipefail

DB_HOST="${DB_HOST:-db}"
DB_PORT="${DB_PORT:-3306}"

echo "Waiting for database to be available"
for i in {1..60} ; do
  # Just doing a nc -z doesn't actually tell us the server is completely ready.
  docker-compose run --rm db mysqladmin ping -h "$DB_HOST" -P "$DB_PORT" >/dev/null 2>&1
  if [ $? -eq 0 ]; then
    echo "Connected to database!" 
    exit
  fi
  sleep 1
done
exit 1